application: 
  host: 0.0.0.0
database:
  require_ssl: true
email_client:
  base_url: "https://api.mailgun.net/v3/sandboxaa41044179704887a4b7edaa0a3f9081.mailgun.org"
  sender_email: "postmaster@sandboxaa41044179704887a4b7edaa0a3f9081.mailgun.org"